In [16]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

scaler = preprocessing.MinMaxScaler()

In [17]:
countries = pd.read_csv("data/countries.csv")
countries = countries.set_index('Unnamed: 0')

In [18]:
yes = scaler.fit_transform(countries[['GDP(2015-2024)','Employment Rate', 'Pop Density', "Population", 'Refugee Population', "Number of CH sights"]])

In [19]:
newdataframe = pd.DataFrame(yes, index = countries.index, columns = ["normGDP",'normEmp', 'normPopDens', "normPop", 'normRef', "normCH"])

In [21]:
result = pd.merge(countries, newdataframe, on="Unnamed: 0")
result

,Latitude,Christian,Muslim,GDP(2015-2024),Employment Rate,Pop Density,Population,Vulnerability score to climate change(ND-Gain index) in 2017,Refugee Population,Number of CH sights,normGDP,normEmp,normPopDens,normPop,normRef,normCH
Unnamed: 0,,,,,,,,,,,,,,,,
Australia,-25.27,67.0,2.4,545163.9,5.3,3.0,2.500000e+07,0.294721,56933.0,20.0,0.468374,0.356164,0.000000,0.015994,0.053514,0.351852
China,35.86,5.1,1.8,NaN,4.4,148.0,1.392000e+09,0.388598,321756.0,55.0,NaN,0.294521,0.018239,1.000000,0.302447,1.000000
Taiwan,23.69,5.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,51.16,69.0,5.8,548869.7,3.2,237.0,8.200000e+07,0.292013,1063837.0,46.0,0.472290,0.212329,0.029434,0.057024,1.000000,0.833333
Hong Kong,22.31,14.0,2.0,NaN,2.8,7096.0,7.450000e+06,NaN,141.0,NaN,NaN,0.184932,0.892201,0.003361,0.000130,NaN
Japan,36.20,1.6,0.2,462456.4,3.7,347.0,1.260000e+08,0.371542,1895.0,23.0,0.380970,0.246575,0.043270,0.088697,0.001778,0.407407
South Korea,35.90,29.4,0.2,NaN,2.4,530.0,5.100000e+07,NaN,2903.0,14.0,NaN,0.157534,0.066289,0.034709,0.002726,0.240741
Netherlands,52.13,50.6,6.0,593066.9,3.7,511.0,1.700000e+07,0.351419,101837.0,10.0,0.518997,0.246575,0.063899,0.010235,0.095724,0.166667
New Zealand,-40.90,57.0,1.2,417001.2,3.7,19.0,4.885000e+06,0.331357,1564.0,3.0,0.332934,0.246575,0.002013,0.001515,0.001467,0.037037
Poland,51.91,94.3,0.0,346151.1,3.3,124.0,3.700000e+07,0.323556,12506.0,16.0,0.258061,0.219178,0.015220,0.024632,0.011753,0.277778
Qatar,25.35,13.8,67.7,NaN,0.1,240.0,2.781000e+06,0.374888,190.0,1.0,NaN,0.000000,0.029811,0.000000,0.000176,0.000000
Russia,61.52,73.3,10.0,306360.0,4.5,9.0,1.440000e+08,0.334639,77397.0,29.0,0.216011,0.301370,0.000755,0.101654,0.072750,0.518519
Singapore,1.35,18.2,14.2,1048225.0,3.6,7953.0,5.638000e+06,0.415255,3.0,1.0,1.000000,0.239726,1.000000,0.002057,0.000000,0.000000
Spain,40.46,78.6,2.1,421150.4,14.7,94.0,4.600000e+07,0.307706,20457.0,48.0,0.337319,1.000000,0.011447,0.031110,0.019227,0.870370
Sweden,60.12,67.2,4.6,557700.4,6.8,25.0,1.000000e+07,0.301165,248266.0,15.0,0.481623,0.458904,0.002767,0.005196,0.233366,0.259259
Ukraine,48.37,83.8,1.2,101955.8,9.3,77.0,4.400000e+07,0.366894,2620.0,7.0,0.000000,0.630137,0.009308,0.029671,0.002460,0.111111
United States,37.09,78.3,0.9,661705.1,3.9,36.0,3.270000e+08,0.338694,313241.0,24.0,0.591533,0.260274,0.004151,0.233382,0.294443,0.425926

So Now all of our data is normalized by minmax, we create our function

In [10]:
countries["Viability"] = 0

In [12]:
a = .3
b = .3
c = .2
d = .2

def viability(country):
    return a*(country["normGDP"]) + b*(1-country['normPopDens'])*(country['normPop']) + c*(country['normEmp']) - d*(country['Vulnerability score to climate change(ND-Gain index) in 2017'])

In [22]:
for i,j in countries.iterrows():
    countries.loc[i , "Viability"]  = viability(result.loc[i])

In [23]:
countries

,Latitude,Christian,Muslim,GDP(2015-2024),Employment Rate,Pop Density,Population,Vulnerability score to climate change(ND-Gain index) in 2017,Refugee Population,Number of CH sights,Viability
Unnamed: 0,,,,,,,,,,,
Australia,-25.27,67.0,2.4,545163.9,5.3,3.0,2.500000e+07,0.294721,56933.0,20.0,0.157599
China,35.86,5.1,1.8,NaN,4.4,148.0,1.392000e+09,0.388598,321756.0,55.0,NaN
Taiwan,23.69,5.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,51.16,69.0,5.8,548869.7,3.2,237.0,8.200000e+07,0.292013,1063837.0,46.0,0.142354
Hong Kong,22.31,14.0,2.0,NaN,2.8,7096.0,7.450000e+06,NaN,141.0,NaN,NaN
Japan,36.20,1.6,0.2,462456.4,3.7,347.0,1.260000e+08,0.371542,1895.0,23.0,0.114755
South Korea,35.90,29.4,0.2,NaN,2.4,530.0,5.100000e+07,NaN,2903.0,14.0,NaN
Netherlands,52.13,50.6,6.0,593066.9,3.7,511.0,1.700000e+07,0.351419,101837.0,10.0,0.137605
New Zealand,-40.90,57.0,1.2,417001.2,3.7,19.0,4.885000e+06,0.331357,1564.0,3.0,0.083377
Poland,51.91,94.3,0.0,346151.1,3.3,124.0,3.700000e+07,0.323556,12506.0,16.0,0.063820
Qatar,25.35,13.8,67.7,NaN,0.1,240.0,2.781000e+06,0.374888,190.0,1.0,NaN
Russia,61.52,73.3,10.0,306360.0,4.5,9.0,1.440000e+08,0.334639,77397.0,29.0,0.088622
Singapore,1.35,18.2,14.2,1048225.0,3.6,7953.0,5.638000e+06,0.415255,3.0,1.0,0.264894
Spain,40.46,78.6,2.1,421150.4,14.7,94.0,4.600000e+07,0.307706,20457.0,48.0,0.248881
Sweden,60.12,67.2,4.6,557700.4,6.8,25.0,1.000000e+07,0.301165,248266.0,15.0,0.177589
Ukraine,48.37,83.8,1.2,101955.8,9.3,77.0,4.400000e+07,0.366894,2620.0,7.0,0.061467
United States,37.09,78.3,0.9,661705.1,3.9,36.0,3.270000e+08,0.338694,313241.0,24.0,0.231500